Repository subhadipbhowmik/30-Days-Of-CPP, pull requests merged in 2024-05, with the labels that each got.

#37 Added the feature to auto comment on a new issue creation
  .github/workflows/auto-comment-on-issue.yml
Labels: gssoc, level1

#35 Added documentation issues templates
  .github/ISSUE_TEMPLATE/documentation.md
Labels: gssoc, level1

#39 Aligned footer
  src/css/custom.css
Labels: gssoc, level1

#43 Modified Tablet View of the Footer
  src/css/custom.css
Labels: gssoc, level1

#45 FIXED #11 : Added Sign-Up and Login Pages
  docusaurus.config.js
  siteConfig.js
  src/css/custom.css
  src/pages/login.md
  src/pages/signup.md
Labels: enhancement, gssoc, level2

#58 Bug Fix : Fixes bug No. #34 UI Glitch
  src/components/HomepageFeatures/index.js
  src/components/HomepageFeatures/styles.module.css
Labels: gssoc, level1

#64 fixed paragraph getting outside of box
  src/components/HomepageFeatures/styles.module.css
Labels: enhancement, gssoc, level1

#69 Added AI Chatbot
  package-lock.json
  package.json
  src/components/Chatbot/chatbot.js
  src/components/Chatbot/style.css
  src/pages/index.js
Labels: enhancement, gssoc, level2

#73 Added Day 4 Content
  docs/day-04/constants-in-cpp.md
Labels: gssoc, level1, content

#80 Day3
  docs/day-01/getting-started-with-cpp.md
  docs/day-01/history-of-cpp.md
  docs/day-01/introduction-to-cpp.md
  docs/day-02/comments-in-cpp.md
  docs/day-02/first-cpp-program.md
  docs/day-02/keywords-identifiers.md
  docs/day-03/cpp-type-modifiers.md
  docs/day-03/datatypes-in-cpp.md
  docs/day-03/variables-literals-constant-in-cpp.md
Labels: good first issue, gssoc, level1

#82 signup/loign pages updated
  src/css/custom.css
  src/pages/login.md
  src/pages/signup.md
Labels: enhancement, gssoc, level1
