Repository subhadipbhowmik/30-Days-Of-CPP, pull requests merged in 2024-07, with the labels that each got.

#401 Added Linear search #254
  docs/day-22/Linear Search.md
  docs/day-22/_category_.json
Labels: bug, enhancement, gssoc, level1

#503 Redesign "Vertical Scrollbar" Matching to the "Website Theme"
  src/pages/index.module.css
Labels: bug, gssoc, level1, content, missing-content

#496 Animation added to the image
  package-lock.json
  src/components/HomepageFeatures/styles.module.css
Labels: bug, gssoc, level1, content, missing-content

#481 Added Preloader
  package-lock.json
  package.json
  src/components/Preloader/Preloader.css
  src/components/Preloader/Preloader.json
  src/components/Preloader/preloader.js
  src/pages/index.js
Labels: bug, enhancement, gssoc, level1, content, missing-content
