Repository subhadipbhowmik/30-Days-Of-CPP, pull requests merged in 2024-06, with the labels that each got.

#84 added custom styles to hero section
  src/pages/index.js
  src/pages/index.module.css
Labels: enhancement, gssoc, level1

#89 Fixes #66
  docs/day-04/operators-in-cpp.md
Labels: enhancement, gssoc, level1

#91 changed login/signup font color in dark mode
  src/css/custom.css
Labels: gssoc, level1

#95 Updated styles to turn off text selection #87 resolved
  src/components/Chatbot/style.css
  src/components/HomepageFeatures/styles.module.css
  src/components/Toast/toastStyles.css
  src/css/custom.css
  src/pages/index.module.css
Labels: enhancement, gssoc, level1

#104 Added Day 4 Content input-output-in-cpp.md
  docs/day-04/input-output-in-cpp.md
Labels: gssoc, level1

#110 Added Day 7 Content - ternary operator
  docs/day-07/ternary-operator.md
Labels: gssoc, level1

#120 Added the Show/Hide Function in the login form
  docs/day-02/first-cpp-program.md
  src/css/custom.css
  src/pages/login.js
  src/pages/login.md
Labels: enhancement, gssoc, level1

#107 Added Content in Day 5 IF-Else Statement
  docs/day-05/if-else-statement.md
Labels: gssoc, level1

#119 Added the content of switch case
  docs/day-07/switch-case-statement.md
Labels: gssoc, level1

#147 fixed-grammatical-error
  docusaurus.config.js
Labels: gssoc, level1

#127 feat: Addition of 'Practice Problems' section to sidebar with topic-specific question pages
  blog/2024-06-03-STL-problems/STL-problems.md
  blog/2024-06-03-array-problems/array-problems.md
  blog/2024-06-03-control-structure-problems/control-structure-problems.md
  blog/2024-06-03-function-problems/function-problems.md
  blog/2024-06-03-introductory-problems/introductory-problems.md
  blog/2024-06-03-sorting-problems/sorting-problems.md
  blog/2024-06-03-string-problems/string-problems.md
  blog/2024-06-03-structure-probelms/structure-problems.md
  blog/authors.yml
Labels: enhancement, gssoc, level1

#151 added scroll bar
  src/css/custom.css
Labels: gssoc, level1

#112 Added Day5 ForLoop Content
  docs/day-05/for-loop.md
Labels: gssoc, level1

#192 Fixes #50
  src/components/HomepageFeatures/styles.module.css
Labels: gssoc, level1

#196 Update do-while-loop.md
  docs/day-05/do-while-loop.md
Labels: gssoc, level1

#155 Day 07 added
  docs/day-07/function-in-cpp.md
Labels: gssoc, level1

#218 Addition of Hide /Show Functionality in the Sign-up page done .
  src/pages/signup.js
Labels: gssoc, level1, content

#172 Day12 - Added Day 12 Content
  docs/day-12/Object_Oriented_Programming.md
  docs/day-12/_category_.json
Labels: gssoc, level1

#221 #189 continue_statement added
  docs/day-06/continue-statement.md
Labels: gssoc, level1, content

#215 Already have an account/ not clearly visible resolved
  src/pages/signup.md
Labels: gssoc, level1

#205 Day 9: Array in Function
  docs/day-09/array-in-function.md
  docs/day-11/reference-in-cpp.md
Labels: gssoc, level1

#204 Issue in autocommenting on merged pr #198
  .github/workflows/auto-comment-pr-merge.yml
Labels: gssoc, level1

#202 fixed color of already have an account
  src/css/custom.css
Labels: enhancement, gssoc, level1

#206 Added operator overloading
  docs/day-04/operators-in-cpp.md
Labels: enhancement, gssoc, level1

#190 Added Day 7 function content
  docs/day-07/function-in-cpp.md
Labels: gssoc, level1

#236 I made changes in dark & light mode
  src/css/custom.css
Labels: enhancement, gssoc, level1, content

#153 Added topic constructors to day 12
  docs/day-12/_category_.json
  docs/day-12/destructors.md
  docs/day-12/introduction.md
  docs/day-12/member-init-list.md
  docs/day-12/types-of-constructors.md
  static/img/day-12/destructors.jpg
  static/img/day-12/introduction.png
  static/img/day-12/member-init-list.png
  static/img/day-12/types-of-constructors.png
Labels: gssoc, level1

#193 Added Social media icons
  docusaurus.config.js
  package-lock.json
  package.json
  src/css/custom.css
  src/pages/index.js
Labels: enhancement, gssoc, level1

#220 Want To Add Backend Of Login/Signup Page #191
  backend/index.js
  backend/package-lock.json
  backend/package.json
  src/pages/login.js
  src/pages/login.md
  src/pages/signup.js
  src/pages/signup.md
Labels: enhancement, gssoc, level1, content

#166 [Feature] : Add more day Course
  docs/day-05/Logical Operators.md
  docs/day-05/arithmetic-Operators.md
  docs/day-05/relational_operators.md
  docs/day-06/If-statement.md
  docs/day-12/Access Specifiers.md
  docs/day-12/Classes and Objects.md
  docs/day-12/_category_.json
  docs/day-12/oops-in-cpp.md
Labels: enhancement, gssoc, level1

#174 Added Day 5 Content do-while-loop.md
  docs/day-05/do-while-loop.md
Labels: gssoc, level1

#181 Added Day 6 Content - goto statement
  docs/day-06/goto-statement.md
Labels: gssoc, level1

#177 footer change and hover it
  src/css/custom.css
Labels: enhancement, gssoc, level1

#231 Issue #55 Resolved
  src/pages/login.js
Labels: enhancement, gssoc, level1, content

#237 Added the contact form
  docusaurus.config.js
  src/components/Contact/Contact.css
  src/components/Contact/Contact.js
  src/pages/index.js
Labels: enhancement, gssoc, level1, content

#239 string class added
  docs/day-10/string-class.md
Labels: enhancement, gssoc, level1, content

#242 done #199
  docusaurus.config.js
Labels: enhancement, gssoc, level1, content

#226 Enhancing Cards on the Home Page
  docs/day-12/pointers_to_structures.md
  docs/day-12/structures.md
  docs/day-12/structures_and_functions.md
  src/components/HomepageFeatures/index.js
  src/components/HomepageFeatures/styles.module.css
Labels: enhancement, gssoc, level1, content

#222 Day 10 string in cpp added
  docs/day-10/string-in-cpp.md
Labels: enhancement, gssoc, level1, content

#188 Added day 5 do while and for loop content
  docs/day-07/function-in-cpp.md
Labels: gssoc, level1

#298 Added returning by reference under day 11
  docs/day-11/returning-by-reference.md
  static/img/day-11/returning-by-reference.png
Labels: enhancement, gssoc, level1

#184 Added Function Overloading
  docs/day-13/Function-overloading.md
  docs/day-13/_category_.json
  static/img/day-13/function-overloading.png
Labels: gssoc, level1

#229 day-14 content added
  docs/day-14/_category_.json
  docs/day-14/constructor.md
  docs/day-14/destructor.md
  docs/day-14/typesofconstructor.md
Labels: enhancement, gssoc, level1, content

#244 added navbar to login page
  src/pages/login.js
Labels: enhancement, gssoc, level1, content

#246 Update day 09 - Array in CPP
  docs/day-09/array-in-cpp.md
Labels: enhancement, gssoc, level1, content

#251 Day-11 content added - Pointer in CPP
  docs/day-11/pointers-in-cpp.md
Labels: enhancement, gssoc, level1, content

#252 Added Daily Tips Feature
  src/components/DailyTips/DailyTips.css
  src/components/DailyTips/DailyTips.js
  src/data/dailyTips.json
  src/pages/index.js
Labels: enhancement, gssoc, level1, content

#262 Added content of recursion
  docs/day-09/recursion-in-cpp.md
Labels: enhancement, gssoc, level1, content

#273 Added Day16
  docs/day-16/_category_.json
  docs/day-16/function-overloading.md
  docs/day-16/operator-overloading.md
Labels: enhancement, gssoc, level1

#274 day12
  docs/day-12/Class and object.md
  docs/day-12/Examples.md
  docs/day-12/_category_.json
  docs/day-12/oops.md
  static/img/day-12/oop1.png
  static/img/day-12/oop2.png
  static/img/day-12/oop3.png
Labels: enhancement, gssoc, level1

#275 Added a "Better Scroll-to-top button" with fixed position
  src/components/ScrollToTop/ScrollToTopButton.js
  src/components/ScrollToTop/ScrollToTopButton.module.css
Labels: enhancement, gssoc, level1

#277 more questions are added related to pointers in array
  docs/day-11/pointers-in-array.md
  package-lock.json
Labels: enhancement, gssoc, level1

#282 Day 11: Pointers in Array in C++
  docs/day-11/pointers-in-cpp.md
Labels: enhancement, gssoc, level1

#283 Added more string question : #267
  blog/2024-06-03-string-problems/string-problems.md
Labels: enhancement, gssoc, level1

#285 Added more sorting question : #284
  blog/2024-06-03-sorting-problems/sorting-problems.md
Labels: enhancement, gssoc, level1

#287 Added Content in Pointers in Array: Fixed #269
  docs/day-10/string-in-cpp.md
  docs/day-11/pointers-in-array.md
Labels: enhancement, gssoc, level1

#288 Fixes #179 : Added Content to Day 15
  docs/day-15/Abstraction.md
  docs/day-15/Encapsulation.md
  docs/day-15/_category_.json
Labels: enhancement, gssoc, level1

#289 Create friend-and-virtual-functions-in-cpp.md
  docs/day-07/friend-and-virtual-functions-in-cpp.md
Labels: enhancement, gssoc, level1

#291 added day-12 content
  docs/day-11/reference-in-cpp.md
  docs/day-12/dma-in-cpp.md
  docs/day-12/introduction-to-dma.md
  docs/day-12/problems-in-dma.md
  static/img/day-12/Introduction.png
  static/img/day-12/dmaInCpp.png
  static/img/day-12/problems.png
Labels: enhancement, gssoc, level1

#292 Added Single Dimensional Array
  docs/day-10/singledimensional-array.md
  static/img/day-10/singledimensional-array.png
Labels: enhancement, gssoc, level1

#293 Added references vs pointers under day 11
  docs/day-11/reference-vs-pointers.md
  static/img/day-11/references-vs-pointers.png
Labels: enhancement, gssoc, level1

#296 Added passing by reference under day 11
  docs/day-11/pass-by-reference.md
  static/img/day-11/passing-by-reference.png
Labels: enhancement, gssoc, level1

#302 multidimentional added
  docs/day-10/multidimentional-array.md
Labels: enhancement, gssoc, level1

#305 #49 Bug is resolved (Updating Footer).
  src/css/custom.css
Labels: enhancement, gssoc, level1

#308 added Day 17
  docs/Day 17/_category.json
  docs/Day 17/exception-handling.md
Labels: enhancement, gssoc, level1

#313 Resolved Allignment and Overlapping of Chatbox and Scroll-to-top button
  package-lock.json
  src/components/ScrollToTop/ScrollToTopButton.module.css
Labels: enhancement, gssoc, level1

#319 Added Blog: Trees Problems
  blog/2024-06-13-tree-problems/tree-problems.md
  blog/authors.yml
  package-lock.json
Labels: enhancement, gssoc, level1

#323 Day 21: Lambda Expressions and Functional Programming in C++
  docs/day-21/Lambda Expressions and Functional Programming copy.md
  docs/day-21/Macros.md
  docs/day-21/_category_.json
  static/img/day-21/Lambda Function.jpg
  static/img/day-21/Macros in cpp.jpg
Labels: enhancement, gssoc, level1

#322 Day 20 Deep Copying vs Shallow Copying
  docs/day-20/Big_Five_In_OOP.md
  docs/day-20/Deep_Copying_vs_Shallow_Copying.md
  docs/day-20/_category_.json
  static/img/day-20/Big Five in OOP.jpg
  static/img/day-20/Day-20-deep_copying_vs_Shallow_Copying.jpg
Labels: enhancement, gssoc, level1

#329 Added Pointers problems: #300
  blog/2024-06-14-pointers-problems/pointers-problem.md
Labels: enhancement, gssoc, level1

#330 Added recursion problem: #301
  blog/2024-06-14-recursion-problem/recursion-problem.md
Labels: enhancement, gssoc, level1

#332 Stylish Scrollbar added
  src/css/custom.css
Labels: bug, enhancement, gssoc, level1

#341 Added Heap Problems in blog
  blog/2024-06-14-heap-problems/HEAP-problems.md
  blog/authors.yml
Labels: bug, enhancement, gssoc, level1

#343 Added Array problems: #307
  blog/2024-06-03-array-problems/array-problems.md
Labels: bug, enhancement, gssoc, level1

#344 Add icons
  docusaurus.config.js
Labels: bug, enhancement, gssoc, level1

#346 Add Day-08 Function Overloading
  docs/day-08/function-overloading.md
  static/img/day-12/Introduction.png
Labels: bug, enhancement, gssoc, level1

#354 added practise problem in cpp #342
  docs/day-20/_category_.json
  docs/day-20/image.png
  docs/day-20/practice-questions.md
Labels: bug, enhancement, gssoc, level1

#367 Fixes #359 : Website Accessible
  docs/day-02/first-cpp-program.md
  docs/day-12/Class and object.md
  docs/day-12/Examples.md
  src/pages/index.js
  src/pages/signup.js
Labels: bug, enhancement, gssoc, level1

#357 Resolved issue overlapping between scroll to top button and chatbot
  src/components/ScrollToTop/ScrollToTopButton.module.css
Labels: bug, enhancement, gssoc, level1

#362 Added Day 11 Pass By Value
  docs/day-11/pass-by-value.md
  docs/day-11/reference-in-cpp.md
  docs/day-11/reference-vs-pointers.md
  docs/day-11/returning-by-reference.md
Labels: bug, enhancement, gssoc, level1

#358 Added Problem related to dynamic programming: #338
  blog/2021-06-15-dynamic-programming/dynamic-programming-problems.md
Labels: bug, enhancement, gssoc, level1

#355 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, enhancement, gssoc, level1

#369 Improvement in backend file structure. #356
  backend/.gitignore
  backend/config/config.js
  backend/controllers/authController.js
  backend/controllers/errorHandler.js
  backend/index.js
  backend/middleware/authMiddleware.js
  backend/middleware/validationMiddleware.js
  backend/models/user.js
  backend/package-lock.json
  backend/package.json
  backend/routers/auth.js
  backend/routers/router.js
Labels: bug, enhancement, gssoc, level2

#370 Day10content: Multidimensional array and string class
  docs/day-10/multidimentional-array.md
  docs/day-10/string-class.md
  docs/day-11/pointers-in-array.md
Labels: bug, enhancement, gssoc, level1

#372 Want to Add More Sorting problems #349
  blog/2024-06-03-function-problems/function-problems.md
Labels: bug, enhancement, gssoc, level1

#373 Added Problem related to Linked List: #352
  blog/2024-06-15-linked-list/linked-list-problems.md
Labels: bug, enhancement, gssoc, level1

#375 Day -14 : C++ Standard Template Library (STL)
  docs/day-14/category_.json
  docs/day-14/stl-algorithms.md
  docs/day-14/stl-containers.md
  docs/day-14/stl-introduction.md
  docs/day-14/stl-iterators.md
Labels: bug, enhancement, gssoc, level1

#377 Add day-18 Linked List
  docs/day-02/first-cpp-program.md
  docs/day-12/Class and object.md
  docs/day-12/Examples.md
  docs/day-18/Linked-List-in-cpp.md
  docs/day-18/Operations-on-linked-list.md
  docs/day-18/_category_.json
  src/pages/index.js
  static/img/day-18/Circular.jpeg
  static/img/day-18/Doubly.jpeg
  static/img/day-18/DoublyCircular.jpeg
  static/img/day-18/Sinlgy.png
Labels: bug, enhancement, gssoc, level1

#383 added-function-problems
  blog/2024-06-03-function-problems/function-problems.md
Labels: enhancement, gssoc, level1

#409 added polymorphism for day 19
  docs/day-19/_category_.json
  docs/day-19/examples.md
  docs/day-19/polymorphism.md
  docs/day-19/types-of-polymorphism.md
  static/img/day-19/poly1.png
  static/img/day-19/poly2.png
  static/img/day-19/poly3.png
Labels: bug, enhancement, gssoc, level1

#412 Added medium level Practise Problems in cpp
  docs/day-25/_category_.json
  docs/day-25/medium-level-questions.md
  docs/day-25/solution.md
Labels: bug, enhancement, gssoc, level1
